### PR TITLE
fixing thread implementation and does run with FreeBSD without Segfaults

### PR DESCRIPTION
**Pull request by dunst0**
Yes there are a lot of changes in this pull request, I know that there is no a great chance that it will make it into the project, but I hope that there are some people who give my fork a try and give me feedback to mistakes, problems, errors or else.

And maybe some parts of my changes will make it into the upstream project. Because there where a lot of wrong memory accesses because of the mistakes in the Thread implementation, right now it doesn't hurt but its not future proof.

Im happy to hear the feedback of the community.

### CODE REVIEW

**Comment by dunst0** [comment]
Travis is a nice guy and reports my mistakes. This is the first good response.

**Comment by juha-h** [comment]
Rick writes:

> Yes there are a lot of changes in this pull request, I know that there
> is no a great chance that it will make it into the project, but I hope
> that there are some people who give my fork a try and give me feedback
> to mistakes, problems, errors or else.

Rick,

Could you replace your large pull request with several where each
request deals with a single issue.

-- Juha

**Comment by szokovacs** [comment]
On 2017-09-06 07:43, juha-h wrote:
> Rick writes:
>
> > Yes there are a lot of changes in this pull request, I know that there
> > is no a great chance that it will make it into the project, but I hope
> > that there are some people who give my fork a try and give me feedback
> > to mistakes, problems, errors or else.
>
> Rick,
>
> Could you replace your large pull request with several where each
> request deals with a single issue.

and also skip the whitespace rearranging, because it makes the diff
unreadable.

tia

Szo

**Comment by dunst0** [comment]
@juha-h I will start breaking it down into smaller pull request. Please keep this one for now open as reference.

@szokovacs I used clang-format to get the code proper formatted, because there where so many different ways of formatting. But sure you are right it makes the diffs hard to read.

**Pull request closed without merging**
