### PR TITLE
propose some code formatting for source

### PR DESCRIPTION
**Pull request by dunst0**
I would like propose some code formatting for the source.  Here is my suggestion for code formatting. Happy to here your feedback.

### CODE REVIEW

**Comment by juha-h** [comment]
Rick writes:

>   * propose some code formatting for source

How does your proposal differ from current formatting?

-- Juha

**Comment by dunst0** [comment]
The current formatting, differs from file to file. Some files have spaces for indention, some have tabs and others have both. So right now it's just an example of how formatting could be done. It depends on the feedback of the community. In the proposed formatting the indention will be done with two spaces. With clang-format the formatting can be done automatically.

**Comment by juha-h** [comment]
Rick writes:

> The current formatting, differs from file to file. Some files have
> spaces for indention, some have tabs and others have both. So right
> now it's just an example of how formatting could be done. It depends
> on the feedback of the community. In the proposed formatting the
> indention will be done with two spaces. With clang-format the
> formatting can be done automatically.

If use of spaces or tabs is not counted, would most of the core source
files pass your proposed format?  If not, what are the most common
differences?

-- Juha

**Comment by juha-h** [comment]
Closed due to lack of response.

**Pull request closed without merging**
