### PR TITLE
Initial Travis CI support

### PR DESCRIPTION
**Pull request by lemenkov**
Hello!
Let's enable Travis-CI - it's cool!

### CODE REVIEW

**Comment by lemenkov** [comment]
Here is how it looks currently.

https://travis-ci.org/lemenkov/sems/builds/107762028

**Comment by lemenkov** [comment]
Interesting - it fails to build with clang

https://travis-ci.org/lemenkov/sems/jobs/107771093

**Comment by linuxmaniac** [comment]
I was planning to do the same thing I did for kamailio project, having a docker image and use travis to build using it

**Comment by lemenkov** [comment]
Ping, @sanchi @juha-h ! :)
What do you think about this?

**Comment by lemenkov** [comment]
Cool, thanks!

**Comment by lemenkov** [comment]
@juha-h unfortunately it's not enough. Someone with admin rights must login to Travis-ci.org. and switch on compilation there. Should be here:

https://travis-ci.org/profile/sems-server

**Pull request merged**
