### PR TITLE
Port to Python3 and add Dockerfile for supported platforms.

### PR DESCRIPTION
**Pull request by hecko**
* Add multiple migrations from Python2 ABI to Python3 ABI
  * Migrate Python2 code to Python3 code
  * Add Dockerfiles for supported platforms
  * Add GitHub Actions Docker images build test tasks

### CODE REVIEW

**Comment by juha-h** [comment]
mod_py/Makefile still has this:
```
PYTHON_VERSION ?= $(shell python -c 'import sys;print sys.version[0:3]')
```
which produces error messages:
```
make[6]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/apps/dsm/mods/mod_py'
  File "<string>", line 1
    import sys;print sys.version[0:3]
               ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
Also checking of just [0:3] does not seem to be OK.

**Comment by juha-h** [comment]
@hecko Now also mod_py build on bookworm worked with some deprecated warnings:
```
make[6]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/apps/dsm/mods/mod_py'
g++ -MMD -g -O2 -ffile-prefix-map=/usr/src/opensipg/trunk/src/opensipg-sems=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -fPIC -std=c++11 -g  -O2  -I/usr/include/python3.11 -fno-strict-aliasing  -DMOD_NAME=\"mod_py\" -I../.. -Wdate-time -D_FORTIFY_SOURCE=2 -DHAVE_XMLRPCPP_SSL -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.8.0"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DWITH_ZRTP -DBUILD_DEFAULT_CACHE -DBUILD_DEFAULT_TIMER -DUNIX -DBUILD_ZRTP_MUTEXES -I/usr/local/include/zrtp  -DPROPAGATE_COREDUMP_SETTINGS -I ../../core  -I ../../../../core -I/usr/include/python3.11 -fno-strict-aliasing  -DMOD_NAME=\"mod_py\" -I../.. -c ModPy.cpp -o ModPy.o
ModPy.cpp: In member function ‘virtual int SCPyModule::preload()’:
ModPy.cpp:70:21: warning: ‘void PyEval_InitThreads()’ is deprecated [-Wdeprecated-declarations]
   70 |   PyEval_InitThreads();
      |   ~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/python3.11/Python.h:95,
                 from ModPy.h:29,
                 from ModPy.cpp:28:
/usr/include/python3.11/ceval.h:132:37: note: declared here
  132 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      |                                     ^~~~~~~~~~~~~~~~~~
ModPy.cpp:116:21: warning: ‘void PyEval_ReleaseLock()’ is deprecated [-Wdeprecated-declarations]
  116 |   PyEval_ReleaseLock();
      |   ~~~~~~~~~~~~~~~~~~^~
/usr/include/python3.11/ceval.h:138:37: note: declared here
  138 | Py_DEPRECATED(3.2) PyAPI_FUNC(void) PyEval_ReleaseLock(void);
      |                                     ^~~~~~~~~~~~~~~~~~
```

**Comment by hecko** [comment]
Yeah, Im aware of the deprecations, but I would rather propose to migrate the deprecations to a different PR - this PR is already quite extensive and starting to be rather difficult to comprehend. For now the deprecations do not limit the software to compile. What do you think?

**Comment by juha-h** [comment]
Yes, fixing the warnings can be later. Now when mod_py compiles, it could be removed from bookworm rules line
```
XCLUDED_DSM_PY_MODULES=mod_aws mod_py
```

**Pull request merged**
