### PR TITLE
Fix compilation errors.

### PR DESCRIPTION
**Pull request by smititelu**
Compiled with 'g++ (Debian 4.9.2-10) 4.9.2' on 'Debian 3.16.36-1+deb8u2'.

Updated to latest Flex 4.6 SDK version:
https://www.adobe.com/devnet/flex/flex-sdk-download.html -> 4.5 isn't listed.

### CODE REVIEW

**Comment by juha-h** [comment]
Stefan Mititelu writes:

> Compiled with 'g++ (Debian 4.9.2-10) 4.9.2' on 'Debian
> 3.16.36-1+deb8u2'.
> Updated to latest Flex 4.6 SDK version:
> https://www.adobe.com/devnet/flex/flex-sdk-download.html -> 4.5 isn't
> listed.

I gave the patch a try on Debian Stretch and core/AmDtmfDetector.cpp
does compile anymore.

What has AmDtmfDetector.cpp to do with Flex?

-- Juha

----------------------------------------------------------

g++ -MMD -c -o AmDtmfDetector.o AmDtmfDetector.cpp -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7.0"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DWITH_ZRTP -DBUILD_ZRTP_MUTEXES -DBUILD_DEFAULT_CACHE -DBUILD_DEFAULT_TIMER -DUNIX -DBUILD_ZRTP_MUTEXES -I/usr/local/include/zrtp  -DPROPAGATE_COREDUMP_SETTINGS -I. -fno-strict-aliasing -DUSE_INTERNAL_RESAMPLER -DUSE_SPANDSP -D__STDC_LIMIT_MACROS -Wall -Wno-reorder -Wno-unused -fPIC -std=c++11 -g   -O2
AmDtmfDetector.cpp: In member function ‘virtual int AmSpanDSPInbandDtmfDetector::streamPut(const unsigned char*, unsigned int, long long unsigned int)’:
AmDtmfDetector.cpp:768:3: error: ‘dtmf_rx’ is not a member of ‘std’
   std::dtmf_rx(rx_state, (const int16_t*) samples, size/2);
   ^~~
AmDtmfDetector.cpp:768:3: note: suggested alternative:
In file included from /usr/include/x86_64-linux-gnu/spandsp.h:82:0,
                 from AmDtmfDetector.h:40,
                 from AmDtmfDetector.cpp:29:
/usr/include/spandsp/dtmf.h:171:19: note:   ‘dtmf_rx’
 SPAN_DECLARE(int) dtmf_rx(dtmf_rx_state_t *s, const int16_t amp[], int samples);
                   ^~~~~~~
Makefile:110: recipe for target 'AmDtmfDetector.o' failed

**Comment by smititelu** [comment]
> I gave the patch a try on Debian Stretch and core/AmDtmfDetector.cpp does compile anymore.

Strange enough... for me it compiles now with or without 'std::', and I can't remember why I put it. I've updated this pull request, without it. Can you give it a try once more?

> What has AmDtmfDetector.cpp to do with Flex?

I guess nothing... the flex comment was for 'apps/rtmp/flash_phone/' part. That one needed flex_sdk to compile and I could only find 4.6 for it.

**Comment by juha-h** [comment]
Stefan Mititelu writes:

> Strange enough... for me it compiles now with or without 'std::', and
> I can't remember why I put it. I've updated this pull request, without
> it. Can you give it a try once more?

I tried with patched Conference.h and it gave these kind of warnings:

/usr/src/orig/sems/apps/conference$ make
g++ -MMD -Wall -Wno-reorder -Wno-unused -fPIC -std=c++11 -g   -O2  -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7-dev-124-g1182fbd1-dirty"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DPROPAGATE_COREDUMP_SETTINGS -I ../../core  -c Conference.cpp -o Conference.o
In file included from Conference.cpp:27:0:
Conference.h:108:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<AmAudioFile> LonelyUserFile;
        ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from ../../core/AmSdp.h:36,
                 from ../../core/AmConfig.h:31,
                 from ../../core/AmApi.h:34,
                 from Conference.h:33,
                 from Conference.cpp:27:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
...

You have to use std::unique_ptr instead of std::auto_ptr:

  Any code using auto_ptr can be mechanically converted to using
  unique_ptr, with move() inserted whenever auto_ptr was being
  "copied".

Check all patches.

-- Juha

**Comment by juha-h** [comment]
I think this issue has already been dealt with.

**Pull request closed without merging**
