### PR TITLE
Update g.729 plugin to use latest bcg729 API

### PR DESCRIPTION
**Pull request by lemenkov**
Hello All!
Use  @BelledonneCommunications bcg729 opensource library instead of a proprietary one.

This patch worked for me for a several years already so let's discuss it once again. I'm using it as a underlying module for early_announce application. No issues were reported so far.

### CODE REVIEW

**Comment by juha-h** [comment]
Directory core/plug-in/g729 has Readme.g729.txt file. It too should be upgraded to explain how to build sems using bcg729 library.

**Comment by lemenkov** [comment]
@juha-h agree. I mislooked this file. I think I'll come up with a better patch later, so please don't merge it for now.

**Comment by lemenkov** [comment]
@juha-h I've updated documentation. Also switched it to markdown.

**Comment by lemenkov** [comment]
Rebased on top of current master (commit 2efa63350bf3e6de1a8dbf76e8d516c7d0229012) and added note about G.729 patent expiration (Sipro site is down at this moment).

**Comment by lemenkov** [comment]
@juha-h @sanchi @linuxmaniac just a friendly ping :)
 
Btw it seems that Debian still doesn't contain bcg729 codec, so there is no changes for Travis necessary at this moment.

**Comment by juha-h** [comment]
Peter Lemenkov writes:

> @juha-h @sanchi @linuxmaniac just a friendly ping :)

Sorry, I have been traveling and missed your pull request.  I gave g729
build a try.  First I installed bcg729 according to README.md:

cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
make
make install

Then I applied your pull request and tried to make sems.  It failed like
this:

make[4]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/core/plug-in/g729'
gcc -MMD -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7.0"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DWITH_ZRTP -DBUILD_ZRTP_MUTEXES -DBUILD_DEFAULT_CACHE -DBUILD_DEFAULT_TIMER -DUNIX -DBUILD_ZRTP_MUTEXES -I/usr/local/include/zrtp  -DPROPAGATE_COREDUMP_SETTINGS -I. -fno-strict-aliasing -DUSE_INTERNAL_RESAMPLER -DUSE_SPANDSP -D__STDC_LIMIT_MACROS -I ../.. -I ../../amci  -Wall -fPIC -g  -O2 -Wall -I/opt/intel/ipp/ipp-samples/speech-codecs/core/usc/include  -c g729.c -o g729.o
g729.c: In function ‘pcm16_2_g729’:
g729.c:136:35: warning: passing argument 2 of ‘bcg729Encoder’ from incompatible pointer type [-Wincompatible-pointer-types]
         bcg729Encoder(codec->enc, in_buf, out_buf, &olen);
                                   ^~~~~~
In file included from g729.c:40:0:
/usr/local/include/bcg729/encoder.h:70:24: note: expected ‘int16_t * {aka short int *}’ but argument is of type ‘unsigned char *’
 BCG729_VISIBILITY void bcg729Encoder(bcg729EncoderChannelContextStruct *encoderChannelContext, int16_t inputFrame[], uint8_t bitStream[], uint8_t *bitStreamLength);
                        ^~~~~~~~~~~~~
g729.c: In function ‘g729_2_pcm16’:
g729.c:164:123: warning: passing argument 7 of ‘bcg729Decoder’ from incompatible pointer type [-Wincompatible-pointer-types]
 _PER_FRAME, 0 /* no erasure */, 0 /* not SID */, 0 /* not RFC3389 */, out_buf);
                                                                       ^~~~~~~
In file included from g729.c:39:0:
/usr/local/include/bcg729/decoder.h:68:24: note: expected ‘int16_t * {aka short int *}’ but argument is of type ‘unsigned char *’
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
gcc -o g729.so g729.o  -shared -lm -ldl -rdynamic -lpthread -lstdc++  /usr/local/lib/libzrtp.a /usr/local/lib/libbn.a -L/opt/intel/ipp/ipp-samples/speech-codecs/_bin/linux32_gcc4/lib -lspeech -lcore -L/opt/intel/ipp/6.1.2.051/ia32/sharedlib/ -lippsc -lipps
/usr/bin/ld: cannot find -lspeech
/usr/bin/ld: cannot find -lcore
/usr/bin/ld: cannot find -lippsc
/usr/bin/ld: cannot find -lipps
collect2: error: ld returned 1 exit status
make[4]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/core/plug-in/g729'
gcc -MMD -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7.0"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DWITH_ZRTP -DBUILD_ZRTP_MUTEXES -DBUILD_DEFAULT_CACHE -DBUILD_DEFAULT_TIMER -DUNIX -DBUILD_ZRTP_MUTEXES -I/usr/local/include/zrtp  -DPROPAGATE_COREDUMP_SETTINGS -I. -fno-strict-aliasing -DUSE_INTERNAL_RESAMPLER -DUSE_SPANDSP -D__STDC_LIMIT_MACROS -I ../.. -I ../../amci  -Wall -fPIC -g  -O2 -Wall -I/opt/intel/ipp/ipp-samples/speech-codecs/core/usc/include  -c g729.c -o g729.o
g729.c: In function ‘pcm16_2_g729’:
g729.c:136:35: warning: passing argument 2 of ‘bcg729Encoder’ from incompatible pointer type [-Wincompatible-pointer-types]
         bcg729Encoder(codec->enc, in_buf, out_buf, &olen);
                                   ^~~~~~
In file included from g729.c:40:0:
/usr/local/include/bcg729/encoder.h:70:24: note: expected ‘int16_t * {aka short int *}’ but argument is of type ‘unsigned char *’
 BCG729_VISIBILITY void bcg729Encoder(bcg729EncoderChannelContextStruct *encoderChannelContext, int16_t inputFrame[], uint8_t bitStream[], uint8_t *bitStreamLength);
                        ^~~~~~~~~~~~~
g729.c: In function ‘g729_2_pcm16’:
g729.c:164:123: warning: passing argument 7 of ‘bcg729Decoder’ from incompatible pointer type [-Wincompatible-pointer-types]
 _PER_FRAME, 0 /* no erasure */, 0 /* not SID */, 0 /* not RFC3389 */, out_buf);
                                                                       ^~~~~~~
In file included from g729.c:39:0:
/usr/local/include/bcg729/decoder.h:68:24: note: expected ‘int16_t * {aka short int *}’ but argument is of type ‘unsigned char *’
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
gcc -o g729.so g729.o  -shared -lm -ldl -rdynamic -lpthread -lstdc++  /usr/local/lib/libzrtp.a /usr/local/lib/libbn.a -L/opt/intel/ipp/ipp-samples/speech-codecs/_bin/linux32_gcc4/lib -lspeech -lcore -L/opt/intel/ipp/6.1.2.051/ia32/sharedlib/ -lippsc -lipps
/usr/bin/ld: cannot find -lspeech
/usr/bin/ld: cannot find -lcore
/usr/bin/ld: cannot find -lippsc
/usr/bin/ld: cannot find -lipps
collect2: error: ld returned 1 exit status
make[4]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/core/plug-in/g729'
gcc -MMD -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7.0"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DWITH_ZRTP -DBUILD_ZRTP_MUTEXES -DBUILD_DEFAULT_CACHE -DBUILD_DEFAULT_TIMER -DUNIX -DBUILD_ZRTP_MUTEXES -I/usr/local/include/zrtp  -DPROPAGATE_COREDUMP_SETTINGS -I. -fno-strict-aliasing -DUSE_INTERNAL_RESAMPLER -DUSE_SPANDSP -D__STDC_LIMIT_MACROS -I ../.. -I ../../amci  -Wall -fPIC -g  -O2 -Wall -I/opt/intel/ipp/ipp-samples/speech-codecs/core/usc/include  -c g729.c -o g729.o
g729.c: In function ‘pcm16_2_g729’:
g729.c:136:35: warning: passing argument 2 of ‘bcg729Encoder’ from incompatible pointer type [-Wincompatible-pointer-types]
         bcg729Encoder(codec->enc, in_buf, out_buf, &olen);
                                   ^~~~~~
In file included from g729.c:40:0:
/usr/local/include/bcg729/encoder.h:70:24: note: expected ‘int16_t * {aka short int *}’ but argument is of type ‘unsigned char *’
 BCG729_VISIBILITY void bcg729Encoder(bcg729EncoderChannelContextStruct *encoderChannelContext, int16_t inputFrame[], uint8_t bitStream[], uint8_t *bitStreamLength);
                        ^~~~~~~~~~~~~
g729.c: In function ‘g729_2_pcm16’:
g729.c:164:123: warning: passing argument 7 of ‘bcg729Decoder’ from incompatible pointer type [-Wincompatible-pointer-types]
 _PER_FRAME, 0 /* no erasure */, 0 /* not SID */, 0 /* not RFC3389 */, out_buf);
                                                                       ^~~~~~~
In file included from g729.c:39:0:
/usr/local/include/bcg729/decoder.h:68:24: note: expected ‘int16_t * {aka short int *}’ but argument is of type ‘unsigned char *’
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
gcc -o g729.so g729.o  -shared -lm -ldl -rdynamic -lpthread -lstdc++  /usr/local/lib/libzrtp.a /usr/local/lib/libbn.a -L/opt/intel/ipp/ipp-samples/speech-codecs/_bin/linux32_gcc4/lib -lspeech -lcore -L/opt/intel/ipp/6.1.2.051/ia32/sharedlib/ -lippsc -lipps
/usr/bin/ld: cannot find -lspeech
/usr/bin/ld: cannot find -lcore
/usr/bin/ld: cannot find -lippsc
/usr/bin/ld: cannot find -lipps
collect2: error: ld returned 1 exit status
../Makefile.audio_module:55: recipe for target 'g729.so' failed

Readme.g729.md reads:

+ 1. Get and install Belledonne Communications [bcg729
+    codec](https://github.com/BelledonneCommunications/bcg729).
+
+ 2. Build bcg729 library:
+
+```
+   configure
+   make
+   make install

Does 1. really also include install according to bcg729/README.md, which
asks to use cmake:

	cmake . -DCMAKE_INSTALL_PREFIX=<prefix> -DCMAKE_PREFIX_PATH=<search_prefixes>
	
	make
	make install

If so, what is step 2?

-- Juha

**Comment by lemenkov** [comment]
Hello, @juha-h.
I've modified Makefile so it can be compiled now. Also I've clarified README (removed a duplicated entry).

**Comment by juha-h** [comment]
Peter Lemenkov writes:

> Hello, @juha-h.
> I've modified Makefile so it can be compiled now. Also I've clarified
> README (removed a duplicated entry).

Peter,

Thanks for your effort. I have trouble in applying your pull request to
a copy of sems master in order to test it before merging it:

$ cd /tmp
$ cp -r /usr/src/orig/sems .
$ wget https://patch-diff.githubusercontent.com/raw/sems-server/sems/pull/13.diff
--2018-01-29 22:09:40--  https://patch-diff.githubusercontent.com/raw/sems-server/sems/pull/13.diff
Resolving patch-diff.githubusercontent.com (patch-diff.githubusercontent.com)... 192.30.255.112, 192.30.255.113
Connecting to patch-diff.githubusercontent.com (patch-diff.githubusercontent.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from patch-diff.githubusercontent.com attempted to set domain to github.com
Length: unspecified [text/plain]
Saving to: ‘13.diff’

13.diff                 [  <=>               ]  15.42K  69.0KB/s    in 0.2s    

2018-01-29 22:09:42 (69.0 KB/s) - ‘13.diff’ saved [15786]

$ cd sems/
$ patch --dry-run < ../13.diff 
checking file CMakeLists.txt
checking file FindBcg729.cmake
checking file CMakeLists.txt
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED
checking file CMakeLists.txt
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED
checking file Makefile
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED
checking file Readme.g729.md
The next patch would delete the file Readme.g729.txt,
which does not exist!  Assume -R? [n] ^C
jh@rautu:/tmp/sems$

Any ideaa why the patch fails or how to apply your pull request to a copy
of sems master?

-- Juha

**Comment by juha-h** [comment]
juha-h writes:

> Thanks for your effort. I have trouble in applying your pull request to
> a copy of sems master in order to test it before merging it:

I got the patch done by adding -p1 flag.

-- Juha

**Comment by juha-h** [comment]
I was now able to make g729 module, but got a few compiler warnings (see below).

Also, since the g729 lib is not included in Debian and may be not in other distros too, would it be possible to use it as static lib ( /usr/local/lib/libbcg729.a)?

-- Juha

make[4]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/core/plug-in/g729'
gcc -MMD -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7.0"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DWITH_ZRTP -DBUILD_ZRTP_MUTEXES -DBUILD_DEFAULT_CACHE -DBUILD_DEFAULT_TIMER -DUNIX -DBUILD_ZRTP_MUTEXES -I/usr/local/include/zrtp  -DPROPAGATE_COREDUMP_SETTINGS -I. -fno-strict-aliasing -DUSE_INTERNAL_RESAMPLER -DUSE_SPANDSP -D__STDC_LIMIT_MACROS -I ../.. -I ../../amci  -Wall -fPIC -g  -O2 -Wall  -c g729.c -o g729.o
g729.c: In function ‘pcm16_2_g729’:
g729.c:136:35: warning: passing argument 2 of ‘bcg729Encoder’ from incompatible pointer type [-Wincompatible-pointer-types]
         bcg729Encoder(codec->enc, in_buf, out_buf, &olen);
                                   ^~~~~~
In file included from g729.c:40:0:
/usr/local/include/bcg729/encoder.h:70:24: note: expected ‘int16_t * {aka short int *}’ but argument is of type ‘unsigned char *’
 BCG729_VISIBILITY void bcg729Encoder(bcg729EncoderChannelContextStruct *encoderChannelContext, int16_t inputFrame[], uint8_t bitStream[], uint8_t *bitStreamLength);
                        ^~~~~~~~~~~~~
g729.c: In function ‘g729_2_pcm16’:
g729.c:164:123: warning: passing argument 7 of ‘bcg729Decoder’ from incompatible pointer type [-Wincompatible-pointer-types]
 c->dec, in_buf, G729_BYTES_PER_FRAME, 0 /* no erasure */, 0 /* not SID */, 0 /* not RFC3389 */, out_buf);
                                                                                                 ^~~~~~~
In file included from g729.c:39:0:
/usr/local/include/bcg729/decoder.h:68:24: note: expected ‘int16_t * {aka short int *}’ but argument is of type ‘unsigned char *’
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
gcc -o g729.so g729.o  -shared -lm -ldl -rdynamic -lpthread -lstdc++  /usr/local/lib/libzrtp.a /usr/local/lib/libbn.a -lm -fPIC -lbcg729
cp g729.so ../../lib/g729.so
make[4]: Leaving directory '/usr/src/opensipg/trunk/src/opensipg-sems/core/plug-in/g729'

**Comment by juha-h** [comment]
In order to get a working static lib, I had to add -fPIC flag to
bcg729/CMakeCache.txt CMAKE_C_FLAGS:

//Flags used by the compiler during all build types.
CMAKE_C_FLAGS:STRING=-fPIC

-- Juha

**Comment by sanchi** [comment]
I have added and updated this MR to fit the current codec interface.

**Comment by lemenkov** [comment]
@sanchi cool, thanks!

**Comment by juha-h** [comment]
I tried to compile g729 plugin on Debian Stretch and got errors (below),
Version of the lib is:

ii  libbcg729-dev:amd 1.0.4+git2018 amd64         Development files for the ITU G.729 comp

--------------------------

``
make[4]: Entering directory '/build/opensipg-sems-1.7.5/core/plug-in/g729'
gcc -MMD -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7.0"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DWITH_ZRTP -DBUILD_ZRTP_MUTEXES -DBUILD_DEFAULT_CACHE -DBUILD_DEFAULT_TIMER -DUNIX -DBUILD_ZRTP_MUTEXES -I/usr/local/include/zrtp  -DPROPAGATE_COREDUMP_SETTINGS -I. -fno-strict-aliasing -DUSE_INTERNAL_RESAMPLER -DUSE_SPANDSP -D__STDC_LIMIT_MACROS -I ../.. -I ../../amci  -Wall -fPIC -g  -O2 -Wall  -c g729.c -o g729.o
g729.c: In function 'g729_create':
g729.c:97:18: error: too few arguments to function 'initBcg729EncoderChannel'
     codec->enc = initBcg729EncoderChannel();
                  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from g729.c:40:0:
/usr/include/bcg729/encoder.h:48:54: note: declared here
 BCG729_VISIBILITY bcg729EncoderChannelContextStruct *initBcg729EncoderChannel(uint8_t enableVAD);
                                                      ^~~~~~~~~~~~~~~~~~~~~~~~
g729.c: In function 'pcm16_2_g729':
g729.c:137:7: error: too few arguments to function 'bcg729Encoder'
       bcg729Encoder(codec->enc, (int16_t*)in_buf, (uint8_t*)out_buf);
       ^~~~~~~~~~~~~
In file included from g729.c:40:0:
/usr/include/bcg729/encoder.h:70:24: note: declared here
 BCG729_VISIBILITY void bcg729Encoder(bcg729EncoderChannelContextStruct *encoderChannelContext, int16_t inputFrame[], uint8_t bitStream[], uint8_t *bitStreamLength);
                        ^~~~~~~~~~~~~
g729.c: In function 'g729_2_pcm16':
g729.c:165:44: warning: passing argument 4 of 'bcg729Decoder' makes integer from pointer without a cast [-Wint-conversion]
       bcg729Decoder(codec->dec, in_buf, 0, (int16_t*)out_buf);
                                            ^
In file included from g729.c:39:0:
/usr/include/bcg729/decoder.h:68:24: note: expected 'uint8_t {aka unsigned char}' but argument is of type 'int16_t * {aka short int *}'
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
g729.c:165:7: error: too few arguments to function 'bcg729Decoder'
       bcg729Decoder(codec->dec, in_buf, 0, (int16_t*)out_buf);
       ^~~~~~~~~~~~~
In file included from g729.c:39:0:
/usr/include/bcg729/decoder.h:68:24: note: declared here
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
../Makefile.audio_module:45: recipe for target 'g729.o' failed
``

**Comment by sanchi** [comment]
from which repository is this package?

**Comment by juha-h** [comment]
juha-h writes:

> ii  libbcg729-dev:amd 1.0.4+git2018 amd64         Development files for the ITU G.729 comp

The lib package mentioned in Readme.g729 is an old version
libbcg729-0_1.0.0-1_amd64.deb from year 2016.  Why didn't use use the
current version available in Debian and other distros?

**Comment by juha-h** [comment]
If Debian version of libbcg729 is not OK for some reason, then I would
suggest using linphone's actively maintained libbcg729:

https://gitlab.linphone.org/BC/public/bcg729

**Comment by lemenkov** [comment]
Btw I have a patch for the recent libbcg version. Will update this PR soon.

**Comment by lemenkov** [comment]
@sanchi @juha-h hello!
I've updated plugin to compile against the latest codec API and enabled it in Travis. Could you please take a look?

**Comment by juha-h** [comment]
I was now able to build sems with G729 codec, but don't have any phone with G729 codec to test if the codec actually works.

**Comment by juha-h** [comment]
I found a G729 UA and test call with sems went OK.  This pull request can be committed after travis checks succeed.

**Comment by lemenkov** [comment]
> I found a G729 UA and test call with sems went OK. This pull request can be committed after travis checks succeed.

Sometimes "nonce_wrong_nonce2" test fails (I see it failed two times in a row when building with Clang). I think it's not related. Anyway I've rebased this PR and it passes the tests now.

**Pull request merged**
