### PR TITLE
Use the same linking vals for main app and test

### PR DESCRIPTION
**Pull request by lemenkov**
Instead of copypasting stuff around let's use FOR loop for setting the
same linking values for both main executable and for testing app.

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>

### CODE REVIEW

**Comment by lemenkov** [comment]
This PR actually triggered an issue fixed in #117.

**Comment by juha-h** [comment]
So when #117 is commited the checks will pass?

**Comment by lemenkov** [comment]
> So when #117 is commited the checks will pass?

Yes it will pass.

**Comment by juha-h** [comment]
Peter Lemenkov writes:

> > So when #117 is commited the checks will pass?
> 
> Yes it will pass.

Done with commits. Thanks.

**Comment by lemenkov** [comment]
@juha-h rebased - all tests are passing now.

**Pull request merged**
