### PR TITLE
apps/mwi: fixing problems from issue #56

### PR DESCRIPTION
**Pull request by dunst0**
As mentioned in issue #56

### CODE REVIEW

**Comment by nwhitehorn** [comment]
This would be great to have in. Any chance of merging?

**Comment by juha-h** [comment]
the tittle is "fixing problems fro issue #56", but this pull requests appears to do more that that, e.g., it introduces a new config file.  the confit file allows choosing if presence server is used.  if there is no presence server, then there cannot be a publish reuest and the app should itself haldle also subcriptions and issue notifies.  so i'm confused what this pull request is all about.

**Comment by nwhitehorn** [comment]
Yes, there is unfortunately some extraneous stuff. The main thing is that, with a presence server, I think it needs to do PUBLISH and not NOTIFY (I am not a SIP expert, but NOTIFY didn't work for me and I had to patch SEMS to working MWI) and the current code unconditionally does NOTIFY. With the patch, it unconditionally does PUBLISH. Maybe that is not the right thing either and it needs to be conditional?

**Comment by juha-h** [comment]
Nathan Whitehorn writes:

> Yes, there is unfortunately some extraneous stuff. The main thing is
> that, with a presence server, I think it needs to do PUBLISH and not
> NOTIFY (I am not a SIP expert, but NOTIFY didn't work for me and I had
> to patch SEMS to working MWI) and the current code unconditionally
> does NOTIFY. With the patch, it unconditionally does PUBLISH. Maybe
> that is not the right thing either and it needs to be conditional?

Yes, if a message is waiting, PUBLISH needs to be sent.  Create a new
pull request that only includes this change.

**Comment by juha-h** [comment]
Waiting for new pull request.

**Pull request closed without merging**
