### PR TITLE
wreorder

### PR DESCRIPTION
**Pull request by lemenkov**
This PR is based on a work made by @scfc - I've just squashed them into one huge commit. It suppresses warnings when build with -wreorder gcc option.

### CODE REVIEW

**Comment by juha-h** [comment]
Huge indeed.  Have you checked and re-checked that there are no typos somewhere?

**Comment by juha-h** [comment]
```
make[3]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/apps/di_dialer'
g++ -MMD -Wall -Wreorder -Wno-unused -fPIC -std=c++11 -g  -O2  -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7-dev-285-gad798e00-dirty"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DPROPAGATE_COREDUMP_SETTINGS -I ../../core  -c DIDial.cpp -o DIDial.o
In file included from DIDial.cpp:1:0:
DIDial.h: In constructor ‘DIDialoutInfo::DIDialoutInfo(const string&, const string&, const string&, const string&)’:
DIDial.h:9:10: warning: ‘DIDialoutInfo::userpart’ will be initialized after [-Wreorder]
   string userpart; // user part for dialout
          ^~~~~~~~
DIDial.h:15:35: warning:   base ‘UACAuthCred’ [-Wreorder]
       UACAuthCred(realm, user, pwd) { }
                                   ^
DIDial.h:10:3: warning:   when initialized here [-Wreorder]
   DIDialoutInfo(const string& userpart,
   ^~~~~~~~~~~~~
```

**Comment by juha-h** [comment]
```
make[5]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/apps/dsm/mods/mod_redis'
g++ -MMD -Wall -Wreorder -Wno-unused -fPIC -std=c++11 -g  -O2  -DMOD_NAME=\"mod_redis\" -I../.. -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7-dev-285-gad798e00-dirty"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DPROPAGATE_COREDUMP_SETTINGS -I ../../core  -I ../../../../core -DMOD_NAME=\"mod_redis\" -I../.. -c DRedisConnection.cpp -o DRedisConnection.o
In file included from DRedisConnection.cpp:1:0:
DRedisConnection.h: In constructor ‘DRedisConnection::DRedisConnection(const DRedisConfig&)’:
DRedisConnection.h:32:17: warning: ‘DRedisConnection::redis_context’ will be initialized after [-Wreorder]
   redisContext* redis_context;
                 ^~~~~~~~~~~~~
DRedisConnection.h:31:18: warning:   ‘DRedisConfig DRedisConnection::cfg’ [-Wreorder]
   DRedisConfig   cfg;
                  ^~~
DRedisConnection.cpp:19:1: warning:   when initialized here [-Wreorder]
 DRedisConnection::DRedisConnection(const DRedisConfig& cfg)
 ^~~~~~~~~~~~~~~~
```

**Comment by juha-h** [comment]
Should this line of Makefile.defs be modified too?
```
CXXFLAGS += -Wall -Wno-reorder -Wno-unused -fPIC -std=c++11 -g $(EXTRA_CXXFLAGS)
```

**Comment by lemenkov** [comment]
> Huge indeed. Have you checked and re-checked that there are no typos somewhere?

Yes, I've just checked it again and it looks fine - only initialization reordering in constructors.

**Comment by lemenkov** [comment]
> ```
> make[5]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/apps/dsm/mods/mod_redis'
> g++ -MMD -Wall -Wreorder -Wno-unused -fPIC -std=c++11 -g  -O2  -DMOD_NAME=\"mod_redis\" -I../.. -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7-dev-285-gad798e00-dirty"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DPROPAGATE_COREDUMP_SETTINGS -I ../../core  -I ../../../../core -DMOD_NAME=\"mod_redis\" -I../.. -c DRedisConnection.cpp -o DRedisConnection.o
> In file included from DRedisConnection.cpp:1:0:
> DRedisConnection.h: In constructor ‘DRedisConnection::DRedisConnection(const DRedisConfig&)’:
> DRedisConnection.h:32:17: warning: ‘DRedisConnection::redis_context’ will be initialized after [-Wreorder]
>    redisContext* redis_context;
>                  ^~~~~~~~~~~~~
> DRedisConnection.h:31:18: warning:   ‘DRedisConfig DRedisConnection::cfg’ [-Wreorder]
>    DRedisConfig   cfg;
>                   ^~~
> DRedisConnection.cpp:19:1: warning:   when initialized here [-Wreorder]
>  DRedisConnection::DRedisConnection(const DRedisConfig& cfg)
>  ^~~~~~~~~~~~~~~~
> ```

Fixed that in a separate commit.

**Comment by lemenkov** [comment]
> -Wno-reorder

Done.

**Comment by lemenkov** [comment]
> ```
> make[3]: Entering directory '/usr/src/opensipg/trunk/src/opensipg-sems/apps/di_dialer'
> g++ -MMD -Wall -Wreorder -Wno-unused -fPIC -std=c++11 -g  -O2  -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7-dev-285-gad798e00-dirty"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DPROPAGATE_COREDUMP_SETTINGS -I ../../core  -c DIDial.cpp -o DIDial.o
> In file included from DIDial.cpp:1:0:
> DIDial.h: In constructor ‘DIDialoutInfo::DIDialoutInfo(const string&, const string&, const string&, const string&)’:
> DIDial.h:9:10: warning: ‘DIDialoutInfo::userpart’ will be initialized after [-Wreorder]
>    string userpart; // user part for dialout
>           ^~~~~~~~
> DIDial.h:15:35: warning:   base ‘UACAuthCred’ [-Wreorder]
>        UACAuthCred(realm, user, pwd) { }
>                                    ^
> DIDial.h:10:3: warning:   when initialized here [-Wreorder]
>    DIDialoutInfo(const string& userpart,
>    ^~~~~~~~~~~~~
> ```

Looks like it's your private code which we don't have access to  :)

**Comment by juha-h** [comment]
Sorry about di_dialer.  It is not mine. I had moved it from apps/examples/ to apps:
```
mv $SRC_DIR/apps/examples/di_dialer $SRC_DIR/apps
```

**Comment by lemenkov** [comment]
> examples

No worries. Meanwhile @sanchi added a few more warnings - I'm addressing them now. Wait for a while.

**Comment by lemenkov** [comment]
OK, I believe it's ready now. Let's wait for tests to pass.

**Comment by juha-h** [comment]
Peter Lemenkov writes:

> OK, I believe it's ready now. Let's wait for tests to pass.

I'll try the build once more.

**Comment by juha-h** [comment]
We now have in Makefile.defs:
```
CXXFLAGS += -Wall -Wreorder -Wno-unused -fPIC -std=c++11 -g $(EXTRA_CXXFLAGS)
```
Is -Wreorder really necessary or does -Wall mean that also reorder warnings are on?

**Comment by juha-h** [comment]
di_dialer warnings are still there.  it would be nice to get them fixed too, since di_dialer is very useful app and could (in my opinion) even be promoted from apps/examples to apps.

**Comment by juha-h** [comment]
I got di_dialer warnings also without -Wreorder flag:
```
g++ -MMD -Wall -Wno-unused -fPIC -std=c++11 -g  -O2  -D_DEBUG -D_THREAD_SAFE -D_REENTRANT -DSEMS_VERSION='"1.7-dev-299-gba31e667-dirty"' -DARCH='"x86_64"' -DOS='"linux"' -DSYSTEM_SAMPLECLOCK_RATE=32000LL -DSEMS_APP_NAME='"sems"' -DUSE_MONITORING -DWITH_ZRTP -DBUILD_DEFAULT_CACHE -DBUILD_DEFAULT_TIMER -DUNIX -DBUILD_ZRTP_MUTEXES -I/usr/local/include/zrtp  -DPROPAGATE_COREDUMP_SETTINGS -I ../../core  -c DIDial.cpp -o DIDial.o
In file included from DIDial.cpp:1:0:
DIDial.h: In constructor ‘DIDialoutInfo::DIDialoutInfo(const string&, const string&, const string&, const string&)’:
DIDial.h:9:10: warning: ‘DIDialoutInfo::userpart’ will be initialized after [-Wreorder]
   string userpart; // user part for dialout
          ^~~~~~~~
DIDial.h:15:35: warning:   base ‘UACAuthCred’ [-Wreorder]
       UACAuthCred(realm, user, pwd) { }
                                   ^
DIDial.h:10:3: warning:   when initialized here [-Wreorder]
   DIDialoutInfo(const string& userpart,
   ^~~~~~~~~~~~~
```

**Comment by lemenkov** [comment]
> We now have in Makefile.defs:
> 
> ```
> CXXFLAGS += -Wall -Wreorder -Wno-unused -fPIC -std=c++11 -g $(EXTRA_CXXFLAGS)
> ```
> 
> Is -Wreorder really necessary or does -Wall mean that also reorder warnings are on?

Removed it since it's not necessary when setting -Wall.

**Comment by lemenkov** [comment]
> di_dialer warnings are still there. it would be nice to get them fixed too, since di_dialer is very useful app and could (in my opinion) even be promoted from apps/examples to apps.

Fixed them (I didn't build neither examples nor tutorials previously).

**Pull request merged**
