### PR TITLE
build for bookworm

### PR DESCRIPTION
**Pull request by gorbyo**
Added configs of build for bookworm (debian 12)

### CODE REVIEW

**Comment by juha-h** [comment]
@gorbyo Thanks for the bookworm build.  I tested and it worked fine.  DSM mod_py would have given a lot of trouble, but it was excluded (already in buster build).  Let's wait for a few days before merge in case some other folks want to test it.

**Comment by denyspozniak** [comment]
@gorbyo thanks for the work! everything looks ok.

**Comment by juha-h** [comment]
How about not excluding mod_py?

**Comment by gorbyo** [comment]
Why not. I'll try to build

**Comment by gorbyo** [comment]
Tested build with mod_py. Looks ok. I cant check how the mod_py work.

**Comment by juha-h** [comment]
I haven't used mod_py, but don't see why it could not be included now when it compiles.

**Comment by gorbyo** [comment]
The pull request should have been updated automatically and ready for merge enabled with mod_py after my fork changed. My previous comment just FYI :)

**Pull request merged**
