### PR TITLE
Use Python2 explicitly

### PR DESCRIPTION
**Pull request by lemenkov**
More and more Linux distributions are switching to Python3 as the default Python interpreter. So /usr/bin/python no longer means Python2. We have to ask for Python2 explicitly.

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>

### CODE REVIEW

**Comment by juha-h** [comment]
Is python2 mandatory for sems or would python3 also work?  What would break with python 3?

**Comment by lemenkov** [comment]
> Is python2 mandatory for sems or would python3 also work? What would break with python 3?

I didn't try it with Python3. I know there are some incompatibilities which could be hard to track and fix. Asking for Python2 is the safest option so far.

**Comment by juha-h** [comment]
Peter Lemenkov writes:

> I didn't try it with Python3. I know there are some incompatibilities
> which could be hard to track and fix. Asking for Python2 is the safest
> option so far.

Yes, but when python2 gets dropped from the next release of (e,g.
debian), all sems tools that use python, stop working.  Not a good
idea.

I would rather check if there is problems with python3 in the tools and
if so, fix them.

**Comment by lemenkov** [comment]
I'm going to close this in favour of combined solution compatible with both Py2 and Py3.

**Pull request closed without merging**
