### PR TITLE
do RTCP conflict avoidance payloads processing (interval: [72,76])

### PR DESCRIPTION
**Pull request by furmur**

### CODE REVIEW

**Comment by lemenkov** [comment]
@sanchi that's the PR I've told you at FOSDEM.

@sanchi @juha-h I believe we need this for handling RTCP-MUX (RFC 5761) properly. At least for receiving. 

For those who curious what's this about see the following links for further details:

* https://webrtcglossary.com/rtcp-mux/
* http://www.juandebravo.com/2017/02/15/rtcp-mux-in-webrtc
* http://blogs.asterisk.org/2017/04/26/rtcp-mux-webrtc/
* https://tools.ietf.org/html/rfc5761

Note that Google Chrome requires RTCP-MUX and rejects older unmixed RTP/RTCP streams. As they said a vast majority of WebRTC clients supports rtcp-mux now.

**Comment by lemenkov** [comment]
Hello All!
Any news here? :)

@juha-h is there anything which prevents from PR from being merged?

**Comment by juha-h** [comment]
Have you tested that rtpc works OK after the commit both when rtcp-mux is enabled and when not?  

What comes to  WebRTC compatibility, doesn't WebRTC require DTLS-SRTPF encryption and many other things in SDP?  I have followed JsSIP discussions and it seems that every new release of Chrome or Firefox causes some SDP related backwards compatibility problem.

**Comment by lemenkov** [comment]
> Have you tested that rtpc works OK after the commit both when rtcp-mux is enabled and when not?

Not yet - will do this or next week.

> What comes to WebRTC compatibility, doesn't WebRTC require DTLS-SRTPF encryption and many other things in SDP? I have followed JsSIP discussions and it seems that every new release of Chrome or Firefox causes some SDP related backwards compatibility problem.

Yeah, they are still a moving target.

**Comment by lemenkov** [comment]
@sanchi so what's the status of this one? Is it superseded by your recent rtcp-mux enhancements?

**Comment by sanchi** [comment]
no, rtp-mux and rctp-mux are two completely different things. I haven't had a close look at this one, but if you have tested and feel comfortable feel free to merge

**Comment by lemenkov** [comment]
> no, rtp-mux and rctp-mux are two completely different things. I haven't had a close look at this one, but if you have tested and feel comfortable feel free to merge

Unfortunately I didn't test it yet. Will do soon (hopefully).

**Pull request closed without merging**
